name: Windows 2019 RDP Workflow

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 120

    steps:
    - name: Download Required Files
      run: |
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        $urls = @(
          "https://storage.curvee.eu.org/start-2019.bat",
          "https://storage.curvee.eu.org/wallpaper.png",
          "https://storage.curvee.eu.org/wallpaper.bat",
          "https://storage.curvee.eu.org/loop.bat"
        )
        foreach ($url in $urls) {
          $fileName = $url.Split("/")[-1]
          Invoke-WebRequest -Uri $url -OutFile $fileName -UseBasicParsing
        }

    - name: Install LocalXpose
      run: |
        Invoke-WebRequest https://github.com/localxpose/localxpose/releases/download/v0.5.0/localxpose-windows-amd64-v0.5.0.exe -OutFile localxpose.exe
        Move-Item -Path .\localxpose.exe -Destination C:\localxpose\localxpose.exe
        echo "LocalXpose installed"

    - name: Authenticate LocalXpose
      run: C:\localxpose\localxpose.exe config --auth-token $Env:LOCALXPOSE_AUTH_TOKEN
      env:
        LOCALXPOSE_AUTH_TOKEN: ${{ secrets.LOCALXPOSE_AUTH_TOKEN }}

    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        copy wallpaper.png C:\Users\Public\Desktop\wallpaper.png
        copy wallpaper.bat C:\Users\Public\Desktop\wallpaper.bat

    - name: Start LocalXpose Tunnel
      run: C:\localxpose\localxpose.exe start --auth-token $Env:LOCALXPOSE_AUTH_TOKEN --subdomain rdp --port 3389
      env:
        LOCALXPOSE_AUTH_TOKEN: ${{ secrets.LOCALXPOSE_AUTH_TOKEN }}

    - name: Start RDP
      run: PowerShell -Command "& {Start-Process 'cmd.exe' -ArgumentList '/c start.bat' -Wait}"

    - name: Verify Workflow Completion
      run: echo "Workflow completed successfully."
